proc import datafile='/home/u59954755/Capstone/Data/Test_Master_dataset.csv' out=master_data replace; run;

proc contents data= master_data; run;

proc means data = master_data; var PRECIPITATION WUI_AREA; run;
   
*Sort the data by grouping variable (county_code);
 proc sort data = master_data; 
  by COUNTY_CODE;
 run;
 
*Compute the means of the variables by grouping variable (county_code);
 proc means data = master_data;
  by COUNTY_CODE;
  var PRECIPITATION WUI_AREA;
 run;

*Call MANOVA procedure with proc glm; 
 PROC GLM data=master_data;          
  CLASS COUNTY_CODE;
  MODEL PRECIPITATION WUI_AREA = COUNTY_CODE/ SS3;       
  MANOVA H = COUNTY_CODE/PRINTE PRINTH; 
  MEANS COUNTY_CODE;                    
 RUN;
 
 *--------------------------------------------------------------------------------------------;
*Sort the data by grouping variable (Fire_ACTIVE_IND);
 proc sort data = master_data; 
  by Fire_ACTIVE_IND;
 run;
 
*Compute the means of the variables by grouping variable (Fire_ACTIVE_IND);
 proc means data = master_data;
  by Fire_ACTIVE_IND;
  var PRECIPITATION Temp_Max;
 run;

*Call MANOVA procedure with proc glm; 
 PROC GLM data=master_data;          
  CLASS Fire_ACTIVE_IND;
  MODEL PRECIPITATION Temp_Max = Fire_ACTIVE_IND/ SS3;       
  MANOVA H = Fire_ACTIVE_IND/PRINTE PRINTH; 
  MEANS Fire_ACTIVE_IND;                    
 RUN;
 
*--------------------------------------------------------------------------------------------;
*Sort the data by grouping variable (COUNTY_CODE);
 proc sort data = master_data; 
  by COUNTY_CODE;
 run;
 
*Compute the means of the variables by grouping variable (COUNTY_CODE);
 proc means data = master_data;
  by COUNTY_CODE;
  var Total_Population Temp_Max;
 run;

*Call MANOVA procedure with proc glm; 
 PROC GLM data=master_data;          
  CLASS COUNTY_CODE;
  MODEL Total_Population Temp_Max = COUNTY_CODE/ SS3;       
  MANOVA H = COUNTY_CODE/PRINTE PRINTH; 
  MEANS COUNTY_CODE;                    
 RUN;
 
 
*-----------------------------------------------------------------------------------------------;

proc import datafile='/home/u59954755/Capstone/Data/A-Team_Master_DataFile_V2_Nov05.csv' out=Final_dataset replace; run;
data capstone.Final_dataset; set Final_dataset; run;
PROC SORT
	DATA=capstone.Final_dataset( KEEP=COUNTY_CODE TEMP_MAX TEMP_MIN PRECIPITATION TOTAL_POPULATION INCOME WILDFIRE_FREQUENCY INCIDENT_ACRES_BURNED TOTAL_FUEL_CONSUMPTION CO2_EMISSIONS_METRICTONNES  )
	OUT=WORK.SCATTERPLOTMATRIXPREP;
	BY COUNTY_CODE;
RUN;

ODS GRAPHICS /
	IMAGEMAP=OFF;

OPTIONS VALIDVARNAME=ANY;

data WORK.SCATTERPLOTMATRIXPREP; set WORK.SCATTERPLOTMATRIXPREP;
 rename TOTAL_POPULATION = POPULATION;
 rename INCIDENT_ACRES_BURNED = ACRES_BURNED;
 rename TOTAL_FUEL_CONSUMPTION = FUEL_CONSUMPTION;
 rename CO2_EMISSIONS_METRICTONNES = CO_Emission_MTon;
Run;


PROC SGSCATTER DATA=WORK.SCATTERPLOTMATRIXPREP;
	TITLE "Scatter Plot Matrix";
*	FOOTNOTE "Generated by SAS (&_SASSERVERNAME, &SYSSCPL) on %TRIM(%QSYSFUNC(DATE(), NLDATE20.)) at %TRIM(%QSYSFUNC(TIME(), NLTIMAP25.))";
	MATRIX TEMP_MAX TEMP_MIN PRECIPITATION POPULATION INCOME WILDFIRE_FREQUENCY ACRES_BURNED FUEL_CONSUMPTION CO_Emission_MTon
		/ GROUP=COUNTY_CODE
		START=TOPLEFT
		ELLIPSE=(ALPHA=0.05 TYPE=PREDICTED)
		LEGEND=(NOBORDER TITLE="Legend" POSITION=BOTTOM )
;
RUN;

* to Conduct correlations and include scatter plots in the analysis. grouping varaibles by INCIDENT_NAME;
proc sort data=capstone.Final_dataset 
		out=Work.SortTempTableSorted;
	by COUNTY_NAME;
run;

proc corr data=Work.SortTempTableSorted pearson nosimple 
		plots(maxpoints=none)=scatter(ellipse=PREDICTION);
	var WILDFIRE_FREQUENCY;
	with TEMP_MAX PRECIPITATION TOTAL_POPULATION CO2_EMISSIONS_METRICTONNES;
	*by COUNTY_NAME;
run;
*-------------------------------------------------------------------------------------------------------------------------------------------------;
*multilinear regression analysis;
proc reg data=capstone.Final_dataset alpha=0.05 
		plots(only)=(diagnostics residuals rstudentbypredicted observedbypredicted);
	model WILDFIRE_FREQUENCY=TEMP_MAX / stb ss1 ss2;
	output out=WORK.REG_STATS lcl=lcl_ ucl=ucl_;
	run;
quit;

*PRECIPITATION TOTAL_POPULATION CO2_EMISSIONS_METRICTONNES ;

*--------------------------------------------------------------------------------------------------------------------;

*Sort the data by grouping variable (COUNTY_CODE);
 proc sort data = capstone.Final_dataset; 
  by COUNTY_CODE;
 run;

*Call MANOVA procedure with proc glm; 
 PROC GLM data=capstone.Final_dataset;          
  CLASS COUNTY_CODE;
  MODEL Wildfire_Frequency Incident_Acres_Burned = COUNTY_CODE/ SS3;       
  MANOVA H = COUNTY_CODE/PRINTE PRINTH; 
  MEANS COUNTY_CODE;                    
 RUN;